/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.sistemajoseabel.vista;


import com.proyecto.sistemajoseabel.ContextoSpring.ContextoSpring1;
import com.proyecto.sistemajoseabel.Servicios.ClienteService;


import com.proyecto.sistemajoseabel.entidades.Cliente;
import com.proyecto.sistemajoseabel.entidades.Produccion;
import com.proyecto.sistemajoseabel.servicios.ProduccionService;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.stereotype.Component;



/**
 *
 * @author ZenBook
 */
@Component

public class Cliente14434345 extends javax.swing.JPanel {
    
 private final ProduccionService serviciopro;

    public Cliente14434345(ProduccionService serviciopro) {
        this.serviciopro = serviciopro;
        
        initComponents();
        cargarClientes();
    }

  
    
    // Código generado por el editor de diseño (no se modifica aquí)
    //...

private void cargarClientes() {
        List<Produccion> producciones = serviciopro.obtenerTodasLasProducciones();
        System.out.println("Clientes encontrados: " + producciones.size());

        DefaultTableModel modelo = (DefaultTableModel) tablaclientes.getModel();
        modelo.setRowCount(0); // Limpia tabla

        for (Produccion produccion : producciones) {
            modelo.addRow(new Object[]{
                produccion.getIdProduccion(),
                produccion.getNombre(),
                produccion.getFechaInicio(),
                produccion.getFechaFin(),
                produccion.getEstado(),
                produccion.getDetalles(),
                produccion.getPedido()
            });
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btnEliminar = new rojeru_san.RSButtonRiple();
        btnNuevo = new rojeru_san.RSButtonRiple();
        btnEditar = new rojeru_san.RSButtonRiple();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaclientes = new RSMaterialComponent.RSTableMetroCustom();

        setPreferredSize(new java.awt.Dimension(1290, 770));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorIcon(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setPhColor(new java.awt.Color(102, 102, 102));
        txtBuscar.setPlaceholder("Buscar...");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 430, 40));

        btnEliminar.setBackground(new java.awt.Color(46, 49, 82));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete (1).png"))); // NOI18N
        btnEliminar.setText(" Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 110, 30));

        btnNuevo.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo.setText(" Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 100, 30));

        btnEditar.setBackground(new java.awt.Color(46, 49, 82));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil (1).png"))); // NOI18N
        btnEditar.setText(" Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 100, 30));

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Tipo de documento", "Numero", "Telefono", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaclientes.setBackgoundHead(new java.awt.Color(46, 49, 82));
        tablaclientes.setBackgoundHover(new java.awt.Color(67, 150, 209));
        tablaclientes.setBorderHead(null);
        tablaclientes.setBorderRows(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tablaclientes.setColorBorderHead(new java.awt.Color(46, 49, 82));
        tablaclientes.setColorBorderRows(new java.awt.Color(46, 49, 82));
        tablaclientes.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaclientes.setColorSecondary(new java.awt.Color(255, 255, 255));
        tablaclientes.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaclientes.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tablaclientes.setFontHead(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tablaclientes.setFontRowHover(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tablaclientes.setFontRowSelect(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tablaclientes.setSelectionBackground(new java.awt.Color(67, 150, 209));
        jScrollPane2.setViewportView(tablaclientes);
        tablaclientes.getColumnModel().getColumn(0).setPreferredWidth(10);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 1050, 420));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        
        
        
      
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int filaSeleccionada = tablaclientes.getSelectedRow();

        if (filaSeleccionada != -1) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este cliente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                int idProduccion = (int) tablaclientes.getValueAt(filaSeleccionada, 0);
                serviciopro.eliminar(idProduccion);
                cargarClientes(); // Recargar la lista de clientes
                JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente para eliminar.");
        }
          
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

 /* java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this); // Obtener el Frame principal
        crear_cliente dialog = new crear_cliente(parent, true, serviciopro);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        cargarClientes(); 
   */
       
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
  
      /*  int filaSeleccionada = tablaclientes.getSelectedRow(); if (filaSeleccionada == -1) { JOptionPane.showMessageDialog(null, "Seleccione un cliente para editar"); } else 
        { int idProduccion = (int) tablaclientes.getValueAt(filaSeleccionada, 0);

if (filaSeleccionada == -1) {
    JOptionPane.showMessageDialog(null, "Seleccione un cliente para editar.");
        } else {
    int idProduccion = Integer.parseInt(tablaclientes.getValueAt(filaSeleccionada, 0).toString()); 
   editar_cliente editar = ContextoSpring1.getContexto().getBean(editar_cliente.class);
    editar.setVisible(true);

        
       
  
}
        }
*/


 

        
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnEditar;
    private rojeru_san.RSButtonRiple btnEliminar;
    private rojeru_san.RSButtonRiple btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSTableMetroCustom tablaclientes;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscar;
    // End of variables declaration//GEN-END:variables


 private void cargarClientesEnTablaFiltrados(List<Cliente> listaClientes) {
        DefaultTableModel modelo = (DefaultTableModel) tablaclientes.getModel();
        modelo.setRowCount(0); // Limpiar la tabla

        for (Cliente cliente : listaClientes) {
            modelo.addRow(new Object[]{
                cliente.getIdcliente(),
                cliente.getNombre(),
                cliente.getApellido(),
                cliente.getIdentificacion(),
                cliente.getNumero(),
                cliente.getTelefono(),
                cliente.getDireccion()
            });
        }

 }

}





