/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.sistemajoseabel.vista;


//import controlador.Contrl_login;

import com.proyecto.sistemajoseabel.Servicios.ServicioCorreo;
import com.proyecto.sistemajoseabel.Servicios.ServicioLogin;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import org.springframework.beans.factory.annotation.Autowired;

import com.proyecto.sistemajoseabel.vista.Contrasena1;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Primary;

import org.springframework.stereotype.Component;

/**
 *
 * @author Personal
*/
@Primary
@Component
public class Contrasena3 extends javax.swing.JFrame {
@Autowired
private ApplicationContext context;

    @Autowired
    private ServicioCorreo Serviciocorreo;

   

 private String correoIngresado;

public void setCorreoIngresado(String correo) {
    this.correoIngresado = correo;
}




   public Contrasena3() {
    initComponents();

       setExtendedState(JFrame.MAXIMIZED_BOTH); 
setLocationRelativeTo(null); 


        
setLayout(new GridBagLayout());
GridBagConstraints gbc = new GridBagConstraints();
gbc.gridx = 0;
gbc.gridy = 0;
gbc.anchor = GridBagConstraints.CENTER; 
add(kGradientPanel1, gbc);


JPanel fondo = new JPanel(new BorderLayout());
fondo.add(kGradientPanel1, BorderLayout.CENTER);
setContentPane(fondo);

    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        txtcodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(239, 248, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/logo azul.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel6.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, 90));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel11.setText("Revisa tu bandeja de entrada");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Codigo");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(29, 30, 51));
        rSMaterialButtonRectangle2.setText("Siguiente ");
        rSMaterialButtonRectangle2.setActionCommand("Siguiente->");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel6.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 420, 50));

        txtcodigo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        jPanel6.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 410, 40));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel8.setText("Introducir otra direccion de correo electronico");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 340, 20));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("Ingresa el codigo de 6 digitos que te hemos enviado a ");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 410, 20));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setText("tu correo electronico");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 410, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setText("Reenviar codigo");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 20));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jLabel13.setText("correos no deseados");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 170, 20));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jLabel14.setText("¿no has recibido el correo? verifica la carpeta de ");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 400, 20));

        kGradientPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 470, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
  String codigoIngresado = txtcodigo.getText().trim();

    if (codigoIngresado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor completa el campo del código.", "Campo vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean esValido = Serviciocorreo.verificarCodigo(correoIngresado, codigoIngresado);


    if (esValido) {
        JOptionPane.showMessageDialog(this, "Código verificado correctamente. Puedes continuar.");
System.out.println("Abrir ventana de cambio de contraseña");
NuevaContrasena cambiar = context.getBean(NuevaContrasena.class);
cambiar.setCorreoIngresado(correoIngresado); // asegurate de tener este método
cambiar.setVisible(true);

    } else {
        JOptionPane.showMessageDialog(this, "El código ingresado es incorrecto. Intenta nuevamente.", "Código incorrecto", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed

    }//GEN-LAST:event_txtcodigoActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
Correo_electronico login = context.getBean(Correo_electronico.class);
        login.setVisible(true);


    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed


  jLabel6.setEnabled(false);
    new Timer(30000, e -> jLabel6.setEnabled(true)).start();

    try {
        boolean esValido = Serviciocorreo.enviarCodigoRecuperacion(correoIngresado); // <- ¡Ya funciona!
        if (esValido) {
            JOptionPane.showMessageDialog(this, "Código reenviado correctamente a tu correo.", "Código reenviado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al reenviar el código. Intenta nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al enviar el código: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }



  

    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */
 
public static void startFrm(ApplicationContext context,  String correo){

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
Contrasena3 ventana3 = context.getBean(Contrasena3.class);
ventana3.setCorreoIngresado(correo); // correo es el que el usuario ingresó
ventana3.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables

    

    
  

}


