/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.proyecto.sistemajoseabel.vista;

import com.proyecto.sistemajoseabel.Servicios.EtapasService;
import com.proyecto.sistemajoseabel.entidades.Asignada;
import com.proyecto.sistemajoseabel.entidades.EstadoEtapa;
import com.proyecto.sistemajoseabel.entidades.EtapaProduccion;
import com.proyecto.sistemajoseabel.entidades.Produccion;

import java.awt.Frame;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Collections;

import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;



/**
 *
 * @author pc
 */

public class EtapaProduccion1 extends javax.swing.JDialog {


     @Autowired
private ApplicationContext context; 
    
private EtapasService servicioEtapa;


public EtapaProduccion1(Frame parent, boolean modal, EtapasService servicioEtapa) {
    super(parent, modal);
    this.servicioEtapa = servicioEtapa;
    initComponents();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombretxt = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel11 = new javax.swing.JLabel();
        usuariostxt3 = new RSMaterialComponent.RSComboBoxMaterial();
        txtinicio = new com.toedter.calendar.JDateChooser();
        txtfinal = new com.toedter.calendar.JDateChooser();
        btnGuardar1 = new rojeru_san.RSButtonRiple();
        btnCancelar1 = new rojeru_san.RSButtonRiple();
        Boxestado1 = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel7 = new javax.swing.JLabel();
        usuariostxt1222 = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 49, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century751 BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Etapa Produccion");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Usuarios responsables:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Fecha final:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Nombre etapa:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        nombretxt.setEditable(false);
        nombretxt.setBackground(new java.awt.Color(255, 255, 255));
        nombretxt.setForeground(new java.awt.Color(0, 0, 0));
        nombretxt.setColorMaterial(new java.awt.Color(0, 0, 0));
        nombretxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombretxt.setPhColor(new java.awt.Color(0, 0, 0));
        nombretxt.setPlaceholder("");
        nombretxt.setSelectionColor(new java.awt.Color(0, 0, 0));
        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });
        jPanel1.add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("Fecha inicio:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        usuariostxt3.setForeground(new java.awt.Color(102, 102, 102));
        usuariostxt3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", " " }));
        usuariostxt3.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        usuariostxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariostxt3ActionPerformed(evt);
            }
        });
        jPanel1.add(usuariostxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        txtinicio.setBackground(new java.awt.Color(255, 255, 255));
        txtinicio.setForeground(new java.awt.Color(255, 255, 255));
        txtinicio.setDateFormatString("y-MM-d");
        txtinicio.setMaxSelectableDate(new java.util.Date(253370786472000L));
        jPanel1.add(txtinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, 30));

        txtfinal.setBackground(new java.awt.Color(255, 255, 255));
        txtfinal.setForeground(new java.awt.Color(255, 255, 255));
        txtfinal.setDateFormatString("y-MM-d");
        jPanel1.add(txtfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 200, 30));

        btnGuardar1.setBackground(new java.awt.Color(46, 49, 82));
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 18)); // NOI18N
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 140, -1));

        btnCancelar1.setBackground(new java.awt.Color(46, 49, 82));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida (1).png"))); // NOI18N
        btnCancelar1.setText("Volver");
        btnCancelar1.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 18)); // NOI18N
        btnCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 140, -1));

        Boxestado1.setForeground(new java.awt.Color(102, 102, 102));
        Boxestado1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "pendiente", "proceso", "completado" }));
        Boxestado1.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        Boxestado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boxestado1ActionPerformed(evt);
            }
        });
        jPanel1.add(Boxestado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        usuariostxt1222.setForeground(new java.awt.Color(102, 102, 102));
        usuariostxt1222.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", " " }));
        usuariostxt1222.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        usuariostxt1222.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariostxt1222ActionPerformed(evt);
            }
        });
        jPanel1.add(usuariostxt1222, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Usuarios responsables:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuariostxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariostxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariostxt3ActionPerformed

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
 String nombre = nombretxt.getText().trim();
String estadoStr = Boxestado1.getSelectedItem().toString();    
String Asignada = usuariostxt3.getSelectedItem().toString();

LocalDate fechaInicio = txtinicio.getDate().toInstant()
    .atZone(ZoneId.systemDefault())
    .toLocalDate();

LocalDate fechaFin = txtfinal.getDate().toInstant()
    .atZone(ZoneId.systemDefault())
    .toLocalDate();

// Validar selección de estado
if (estadoStr.equals("Seleccione estado")) {
    JOptionPane.showMessageDialog(this, "Por favor seleccione un estado válido.");
    return;
}

EstadoEtapa estadoEtapa;
try {
    estadoEtapa = EstadoEtapa.valueOf(estadoStr.toUpperCase()); // Asegúrate que coincida con los enum
} catch (IllegalArgumentException ex) {
    JOptionPane.showMessageDialog(this, "Estado no válido.");
    return;
}

Produccion produccion = (Produccion) usuariostxt3.getSelectedItem();
Asignada asignaciones = (Asignada) usuariostxt1222.getSelectedItem();

EtapaProduccion nuevaetapa = new EtapaProduccion();
nuevaetapa.setNombreEtapa(nombre);
nuevaetapa.setEstado(estadoEtapa);
nuevaetapa.setFechaInicio(fechaInicio);
nuevaetapa.setFechaFin(fechaFin);
nuevaetapa.setProduccion(produccion);
nuevaetapa.setAsignaciones(Collections.singletonList(asignaciones));

try {
    servicioEtapa.guardar(nuevaetapa);
    JOptionPane.showMessageDialog(this, "Etapa de producción guardada exitosamente.");
    dispose();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al guardar la etapa: " + e.getMessage());
}

    
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void Boxestado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boxestado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boxestado1ActionPerformed

    private void usuariostxt1222ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariostxt1222ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariostxt1222ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void startFrm(ApplicationContext context) {
       java.awt.EventQueue.invokeLater(() -> {
        EtapaProduccion1 ventana = context.getBean(EtapaProduccion1.class);
        ventana.setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBoxMaterial Boxestado1;
    private rojeru_san.RSButtonRiple btnCancelar1;
    private rojeru_san.RSButtonRiple btnGuardar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private RSMaterialComponent.RSTextFieldMaterial nombretxt;
    private com.toedter.calendar.JDateChooser txtfinal;
    private com.toedter.calendar.JDateChooser txtinicio;
    private RSMaterialComponent.RSComboBoxMaterial usuariostxt1222;
    private RSMaterialComponent.RSComboBoxMaterial usuariostxt3;
    // End of variables declaration//GEN-END:variables
}
