/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.sistemajoseabel.vista;


//import controlador.Contrl_login;

import com.proyecto.sistemajoseabel.Servicios.ServicioCorreo;
import com.proyecto.sistemajoseabel.Servicios.ServicioLogin;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import org.springframework.beans.factory.annotation.Autowired;

import com.proyecto.sistemajoseabel.vista.Contrasena1;
import javax.swing.ImageIcon;
import org.springframework.context.ApplicationContext;

import org.springframework.stereotype.Component;

/**
 *
 * @author Personal
*/
@Component
public class NuevaContrasena extends javax.swing.JFrame {
@Autowired
private ApplicationContext context;

 private String correoIngresado = "";

    public void setCorreoIngresado(String correo) {
        this.correoIngresado = correo;
    };

      @Autowired
    private ServicioLogin servicioLogin;
private boolean isPasswordVisible = false;
      // Rutas de las imágenes
    private final String eyeOpenPath = "/vista (1).png";   // Ojo abierto
    private final String eyeClosedPath = "/ojo (2).png"; // Ojo cerrado
    
    private ImageIcon eyeOpenIcon;
    private ImageIcon eyeClosedIcon;

   public NuevaContrasena() {
    initComponents();

       setExtendedState(JFrame.MAXIMIZED_BOTH); 
setLocationRelativeTo(null); 


        
setLayout(new GridBagLayout());
GridBagConstraints gbc = new GridBagConstraints();
gbc.gridx = 0;
gbc.gridy = 0;
gbc.anchor = GridBagConstraints.CENTER; 
add(kGradientPanel1, gbc);


JPanel fondo = new JPanel(new BorderLayout());
fondo.add(kGradientPanel1, BorderLayout.CENTER);
setContentPane(fondo);

    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iniciar = new RSMaterialComponent.RSButtonShape();
        btnVer = new rojeru_san.RSButton();
        txtcontrasenanueva = new RSMaterialComponent.RSPasswordIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(239, 248, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/logo azul.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel6.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, 90));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel11.setText("Cambia tu contraseña");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Contraseña");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel8.setText("volver al inicio de sesion");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 170, 20));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("Escribe tu nueva contraseña, recuerda que debe tener");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 410, 20));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setText("8 digitos");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 410, 20));

        iniciar.setBackground(new java.awt.Color(29, 30, 51));
        iniciar.setText("                                                   Continuar");
        iniciar.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jPanel6.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 410, 40));

        btnVer.setBackground(new java.awt.Color(236, 236, 236));
        btnVer.setColorHover(new java.awt.Color(247, 247, 247));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel6.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 40, 40));

        txtcontrasenanueva.setForeground(new java.awt.Color(0, 0, 0));
        txtcontrasenanueva.setToolTipText("");
        txtcontrasenanueva.setBorderColor(new java.awt.Color(230, 230, 230));
        txtcontrasenanueva.setColorIcon(new java.awt.Color(204, 204, 204));
        txtcontrasenanueva.setPhColor(new java.awt.Color(51, 51, 51));
        txtcontrasenanueva.setPlaceholder("Ingrese su contraseña");
        txtcontrasenanueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenanuevaActionPerformed(evt);
            }
        });
        jPanel6.add(txtcontrasenanueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 390, 40));

        kGradientPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 470, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed

    }//GEN-LAST:event_jLabel8MousePressed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
  String nuevaContrasena = txtcontrasenanueva.getText().trim();

    if (nuevaContrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese una nueva contraseña.");
        return;
    }

    boolean cambioExitoso = servicioLogin.cambiarContrasena(correoIngresado, nuevaContrasena);

    if (cambioExitoso) {
        JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente. Inicia sesión.");
        this.dispose();
        Login11211 login = context.getBean(Login11211.class);
        login.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró el usuario. Intenta de nuevo.");
    }

    }//GEN-LAST:event_iniciarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        togglePasswordVisibility();
    }//GEN-LAST:event_btnVerActionPerformed

    private void txtcontrasenanuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenanuevaActionPerformed

    }//GEN-LAST:event_txtcontrasenanuevaActionPerformed

    /**
     * @param context
     * @param args the command line arguments
     */
 
public static void startFrm(ApplicationContext context){

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
 NuevaContrasena ventana = context.getBean(NuevaContrasena.class);
ventana.setCorreoIngresado("");
ventana.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnVer;
    private RSMaterialComponent.RSButtonShape iniciar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private RSMaterialComponent.RSPasswordIconOne txtcontrasenanueva;
    // End of variables declaration//GEN-END:variables

    

      private void togglePasswordVisibility() {
        if (isPasswordVisible) {
            txtcontrasenanueva.setEchoChar('•'); // Ocultar contraseña
            btnVer.setIcon(eyeClosedIcon); // Cambiar a imagen de ojo cerrado

        } else {
            txtcontrasenanueva.setEchoChar((char) 0); // Mostrar contraseña
            btnVer.setIcon(eyeOpenIcon); // Cambiar a imagen de ojo abierto
        }
        isPasswordVisible = !isPasswordVisible;
    }
  

}


