/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.sistemajoseabel.vista;

import com.proyecto.sistemajoseabel.Servicios.ServicioLogin;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


/**
 *
 * @author Personal
 */

@Component
public class Login11211 extends javax.swing.JFrame {
 private boolean isPasswordVisible = false;
      // Rutas de las imágenes
    private final String eyeOpenPath = "/vista (1).png";   // Ojo abierto
    private final String eyeClosedPath = "/ojo (2).png"; // Ojo cerrado
    
    private ImageIcon eyeOpenIcon;
    private ImageIcon eyeClosedIcon;
    /**
     * Creates new form Login1
     */
     @Autowired
    private ServicioLogin servicioLogin;
    public Login11211() {
        initComponents();
setLocationRelativeTo(null); 



setLayout(new GridBagLayout());
GridBagConstraints gbc = new GridBagConstraints();
gbc.gridx = 0;
gbc.gridy = 0;
gbc.anchor = GridBagConstraints.CENTER; 
add(kGradientPanel1, gbc);


JPanel fondo = new JPanel(new BorderLayout());
fondo.add(kGradientPanel1, BorderLayout.CENTER);
setContentPane(fondo);


    }
    
    private void togglePasswordVisibility() {
        if (isPasswordVisible) {
            passtxt.setEchoChar('•'); // Ocultar contraseña
            btnVer.setIcon(eyeClosedIcon); // Cambiar a imagen de ojo cerrado

        } else {
            passtxt.setEchoChar((char) 0); // Mostrar contraseña
            btnVer.setIcon(eyeOpenIcon); // Cambiar a imagen de ojo abierto
        }
        isPasswordVisible = !isPasswordVisible;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel7 = new javax.swing.JLabel();
        txt_usuario = new RSMaterialComponent.RSTextFieldIconOne();
        jLabel6 = new javax.swing.JLabel();
        passtxt = new RSMaterialComponent.RSPasswordIconOne();
        jLabel2 = new javax.swing.JLabel();
        btnVer = new rojeru_san.RSButton();
        rSPanelImage3 = new rojerusan.RSPanelImage();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        jLabel13 = new javax.swing.JLabel();
        rSButtonShape1 = new RSMaterialComponent.RSButtonShape();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(239, 248, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/logo azul.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        kGradientPanel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, 250, 230));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Usuario");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 470, -1, 20));

        txt_usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_usuario.setBorderColor(new java.awt.Color(230, 230, 230));
        txt_usuario.setColorIcon(new java.awt.Color(204, 204, 204));
        txt_usuario.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txt_usuario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        txt_usuario.setPhColor(new java.awt.Color(51, 51, 51));
        txt_usuario.setPlaceholder("ingrese su usuario");
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, 360, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("Contraseña");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, -1, -1));

        passtxt.setForeground(new java.awt.Color(0, 0, 0));
        passtxt.setToolTipText("");
        passtxt.setBorderColor(new java.awt.Color(230, 230, 230));
        passtxt.setColorIcon(new java.awt.Color(204, 204, 204));
        passtxt.setPhColor(new java.awt.Color(51, 51, 51));
        passtxt.setPlaceholder("Ingrese su contraseña");
        kGradientPanel1.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 570, 360, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 30, 51));
        jLabel2.setText("¿Olvidaste contraseña?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 600, -1, -1));

        btnVer.setBackground(new java.awt.Color(236, 236, 236));
        btnVer.setColorHover(new java.awt.Color(247, 247, 247));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 570, 30, 30));

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Vector 6.png"))); // NOI18N
        rSPanelImage3.setLayout(null);

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp_Image_2025-03-28_at_10.59.04_AM-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        rSPanelImage3.add(rSPanelImage2);
        rSPanelImage2.setBounds(250, -10, 610, 540);

        kGradientPanel1.add(rSPanelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 890, 690));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(29, 30, 51));
        jLabel13.setText("Iniciar Sesión");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 340, 320, -1));

        rSButtonShape1.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonShape1.setText("                                               Ingresar");
        rSButtonShape1.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        rSButtonShape1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShape1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSButtonShape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 660, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        togglePasswordVisibility();
    }//GEN-LAST:event_btnVerActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        /*Contrasena1 dialog = new Contrasena1(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);*/

    }//GEN-LAST:event_jLabel2MousePressed

    private void rSButtonShape1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShape1ActionPerformed
       autenticarUsuario();
    }//GEN-LAST:event_rSButtonShape1ActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void startFrm(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1121.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1121.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1121.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1121.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login11211().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnVer;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private RSMaterialComponent.RSPasswordIconOne passtxt;
    private RSMaterialComponent.RSButtonShape rSButtonShape1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    private rojerusan.RSPanelImage rSPanelImage3;
    private RSMaterialComponent.RSTextFieldIconOne txt_usuario;
    // End of variables declaration//GEN-END:variables

private void autenticarUsuario() {
    String usuario = txt_usuario.getText();
    String contrasena = new String(passtxt.getPassword());

    if (servicioLogin.autenticar(usuario, contrasena)) {
        // Crear la pantalla de carga
        kla cargando = new kla(new JFrame(), true);

        new Thread(() -> {
            cargando.setVisible(true);
        }).start();

        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {
            cargando.dispose();

            JOptionPane.showMessageDialog(this, "Acceso concedido");

            // Abrir ventana principal
            Principal11 pc = new Principal11();
            pc.setVisible(true);

            // Cerrar login
            this.dispose();
        });

        timer.setRepeats(false); // Solo una vez
        timer.start();

    } else {
        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
        System.out.println("ServicioLogin inyectado: " + (servicioLogin != null));
    }
}
}

